### ISSUE TITLE
missing README

### ISSUE THREAD

**Issue by coolaj86** [tigerbot/bo#1]
```
Install
=====

git@github.com:tigerbot/bo.git

chmod a+x *.sh

./build.sh

Run
===

./bin/bo_server

http://localhost.daplie.me:8000
```

**Comment by lastlink** [comment]
Wouldn't this be better as a pull request?

**Comment by coolaj86** [comment]
Yes, but I wanted to make sure you had something to do as well... I’m kinda surprised that you’re only just now getting around to it - it’s been a longstanding opportunity.

**Comment by lastlink** [comment]
@coolaj86 I don't have write access to this repo, I just remember staring it a while back and am planning on next year running an oauth2 server w/ some web apps from home as oauth clients for random things like financial planner and games that I can access via a vpn. I was planning on using daplie for some of these things, but they keep delaying their release. I noticed that you've pivoted to another home server called ppl.
